import {
    YouVersionBibleDataInterface,
    YouVersionPassageInterface,
    YouVersionVerseOfTheDayInterface,
} from '@/types/app.types';

export const YOU_VERSION_API_KEY =
    'OildLQptM8TGYe4wEfYfdo0fA61pE23odZXAAjSm7kSCGA7F';

export const YOU_VERSION_BASE_URL = 'https://api.youversion.com/v1';

export const DEFAULT_PASSAGE_ID: string = 'JHN.3.16';
export const DEFAULT_VOTD: YouVersionVerseOfTheDayInterface = {
    day: 1,
    passage_id: DEFAULT_PASSAGE_ID,
};
export const DEFAULT_PASSAGE: YouVersionPassageInterface = {
    id: DEFAULT_PASSAGE_ID,
    content:
        'For God so loved the world that he gave his only-begotten Son, so that all who believe in him may not perish, but may have eternal life.',
    reference: 'John 3:16',
};

export const DEFAULT_BIBLE_DATA: YouVersionBibleDataInterface = {
    id: 3034,
    abbreviation: 'BSB',
    promotional_content: 'Public Domain',
    copyright: 'Public Domain',
    info: null,
    publisher_url: null,
    language_tag: 'en',
    localized_abbreviation: 'BSB',
    localized_title: 'Berean Standard Bible',
    title: 'Berean Standard Bible',
    books: [
        'GEN',
        'EXO',
        'LEV',
        'NUM',
        'DEU',
        'JOS',
        'JDG',
        'RUT',
        '1SA',
        '2SA',
        '1KI',
        '2KI',
        '1CH',
        '2CH',
        'EZR',
        'NEH',
        'EST',
        'JOB',
        'PSA',
        'PRO',
        'ECC',
        'SNG',
        'ISA',
        'JER',
        'LAM',
        'EZK',
        'DAN',
        'HOS',
        'JOL',
        'AMO',
        'OBA',
        'JON',
        'MIC',
        'NAM',
        'HAB',
        'ZEP',
        'HAG',
        'ZEC',
        'MAL',
        'MAT',
        'MRK',
        'LUK',
        'JHN',
        'ACT',
        'ROM',
        '1CO',
        '2CO',
        'GAL',
        'EPH',
        'PHP',
        'COL',
        '1TH',
        '2TH',
        '1TI',
        '2TI',
        'TIT',
        'PHM',
        'HEB',
        'JAS',
        '1PE',
        '2PE',
        '1JN',
        '2JN',
        '3JN',
        'JUD',
        'REV',
    ],
    youversion_deep_link: 'https://www.bible.com/versions/3034',
    organization_id: 'c3187cfe-a191-4088-9fb2-24c306d9eb38',
};
