import { useFonts } from 'expo-font';

export default function useAppFonts() {
    return useFonts({
        'googlesans-bold': require('../../assets/fonts/GoogleSans-Bold.ttf'),
        'googlesans-bolditalic': require('../../assets/fonts/GoogleSans-BoldItalic.ttf'),
        'googlesans-italic': require('../../assets/fonts/GoogleSans-Italic.ttf'),
        'googlesans-medium': require('../../assets/fonts/GoogleSans-Medium.ttf'),
        'googlesans-mediumitalic': require('../../assets/fonts/GoogleSans-MediumItalic.ttf'),
        'googlesans-regular': require('../../assets/fonts/GoogleSans-Regular.ttf'),
        'googlesans-semibold': require('../../assets/fonts/GoogleSans-SemiBold.ttf'),
        'googlesans-semibolditalic': require('../../assets/fonts/GoogleSans-SemiBoldItalic.ttf'),
        'literata-black': require('../../assets/fonts/Literata-Black.ttf'),
        'literata-blackitalic': require('../../assets/fonts/Literata-BlackItalic.ttf'),
        'literata-bold': require('../../assets/fonts/Literata-Bold.ttf'),
        'literata-bolditalic': require('../../assets/fonts/Literata-BoldItalic.ttf'),
        'literata-extrabold': require('../../assets/fonts/Literata-ExtraBold.ttf'),
        'literata-extrabolditalic': require('../../assets/fonts/Literata-ExtraBoldItalic.ttf'),
        'literata-extralight': require('../../assets/fonts/Literata-ExtraLight.ttf'),
        'literata-extralightitalic': require('../../assets/fonts/Literata-ExtraLightItalic.ttf'),
        'literata-italic': require('../../assets/fonts/Literata-Italic.ttf'),
        'literata-light': require('../../assets/fonts/Literata-Light.ttf'),
        'literata-lightitalic': require('../../assets/fonts/Literata-LightItalic.ttf'),
        'literata-medium': require('../../assets/fonts/Literata-Medium.ttf'),
        'literata-mediumitalic': require('../../assets/fonts/Literata-MediumItalic.ttf'),
        'literata-regular': require('../../assets/fonts/Literata-Regular.ttf'),
        'literata-semibold': require('../../assets/fonts/Literata-SemiBold.ttf'),
        'literata-semibolditalic': require('../../assets/fonts/Literata-SemiBoldItalic.ttf'),
        'quicksand-bold': require('../../assets/fonts/Quicksand-Bold.ttf'),
        'quicksand-light': require('../../assets/fonts/Quicksand-Light.ttf'),
        'quicksand-medium': require('../../assets/fonts/Quicksand-Medium.ttf'),
        'quicksand-regular': require('../../assets/fonts/Quicksand-Regular.ttf'),
        'quicksand-semibold': require('../../assets/fonts/Quicksand-SemiBold.ttf'),
        'robotomono-bold': require('../../assets/fonts/RobotoMono-Bold.ttf'),
        'robotomono-bolditalic': require('../../assets/fonts/RobotoMono-BoldItalic.ttf'),
        'robotomono-extralight': require('../../assets/fonts/RobotoMono-ExtraLight.ttf'),
        'robotomono-extralightitalic': require('../../assets/fonts/RobotoMono-ExtraLightItalic.ttf'),
        'robotomono-italic': require('../../assets/fonts/RobotoMono-Italic.ttf'),
        'robotomono-light': require('../../assets/fonts/RobotoMono-Light.ttf'),
        'robotomono-lightitalic': require('../../assets/fonts/RobotoMono-LightItalic.ttf'),
        'robotomono-medium': require('../../assets/fonts/RobotoMono-Medium.ttf'),
        'robotomono-mediumitalic': require('../../assets/fonts/RobotoMono-MediumItalic.ttf'),
        'robotomono-regular': require('../../assets/fonts/RobotoMono-Regular.ttf'),
        'robotomono-semibold': require('../../assets/fonts/RobotoMono-SemiBold.ttf'),
        'robotomono-semibolditalic': require('../../assets/fonts/RobotoMono-SemiBoldItalic.ttf'),
        'robotomono-thin': require('../../assets/fonts/RobotoMono-Thin.ttf'),
        'robotomono-thinitalic': require('../../assets/fonts/RobotoMono-ThinItalic.ttf'),
    });
}
